_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 12
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 12
                - 53
                - 55
                - 77
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.10
            "8":
                - 1
                - 5
            "10":
                - 20
            "12": 0.19.10
            "13": darwin-arm64
